site_name: Entlang der Donau ans Schwarze Meer und über die Karpaten.
site_url: https://stefanhoelzl.github.io/danube-carpathian-mountains-by-bike/
theme:
  name: mkdocs
  include_sidebar: false
  color_mode: auto
plugins: []
extra_css:
  - extra.css
hooks:
  - hooks/track.py
